

var data = [
    {"code": 10001, "name": "Avalon "},
    {"code": 10002, "name": "Bonavista-Burin-Trinity"},
    {"code": 10003, "name": "Coast of Bays-Central-Notre Dame"},
    {"code": 10004, "name": "Labrador"},
    {"code": 10005, "name": "Long Range Mountains"},
    {"code": 10006, "name": "St. John\'s East"},
    {"code": 10007, "name": "St. John\'s South-Mount Pearl"},
    {"code": 11001, "name": "Cardigan"},
    {"code": 11002, "name": "Charlottetown"},
    {"code": 11003, "name": "Egmont"},
    {"code": 11004, "name": "Malpeque"},
    {"code": 12001, "name": "Cape Breton-Canso"},
    {"code": 12002, "name": "Central Nova"},
    {"code": 12003, "name": "Cumberland-Colchester"},
    {"code": 12004, "name": "Dartmouth-Cole Harbour"},
    {"code": 12005, "name": "Halifax"},
    {"code": 12006, "name": "Halifax West"},
    {"code": 12007, "name": "Kings-Hants"},
    {"code": 12008, "name": "Sackville-Preston-Chezzetcook"},
    {"code": 12009, "name": "South Shore-St. Margarets"},
    {"code": 12010, "name": "Sydney-Victoria"},
    {"code": 12011, "name": "West Nova"},
    {"code": 13001, "name": "Acadie-Bathurst"},
    {"code": 13002, "name": "Beauséjour"},
    {"code": 13003, "name": "Fredericton"},
    {"code": 13004, "name": "Fundy Royal"},
    {"code": 13005, "name": "Madawaska-Restigouche"},
    {"code": 13006, "name": "Miramichi-Grand Lake"},
    {"code": 13007, "name": "Moncton-Riverview-Dieppe"},
    {"code": 13008, "name": "New Brunswick Southwest"},
    {"code": 13009, "name": "Saint John-Rothesay"},
    {"code": 13010, "name": "Tobique-Mactaquac"},
    {"code": 24001, "name": "Abitibi-Baie-James-Nunavik-Eeyou"},
    {"code": 24002, "name": "Abitibi-Témiscamingue"},
    {"code": 24003, "name": "Ahuntsic-Cartierville"},
    {"code": 24004, "name": "Alfred-Pellan"},
    {"code": 24005, "name": "Argenteuil-La Petite-Nation"},
    {"code": 24006, "name": "Avignon-La Mitis-Matane-Matapédia"},
    {"code": 24007, "name": "Beauce"},
    {"code": 24020, "name": "Beauport-Côte-de-Beaupré-Île d’Orléans-Charlevoix"},
    {"code": 24008, "name": "Beauport-Limoilou"},
    {"code": 24009, "name": "Bécancour-Nicolet-Saurel"},
    {"code": 24010, "name": "Bellechasse-Les Etchemins-Lévis"},
    {"code": 24011, "name": "Beloeil-Chambly"},
    {"code": 24012, "name": "Berthier-Maskinongé"},
    {"code": 24015, "name": "Bourassa"},
    {"code": 24016, "name": "Brome-Missisquoi"},
    {"code": 24017, "name": "Brossard-Saint-Lambert"},
    {"code": 24019, "name": "Charlesbourg-Haute-Saint-Charles"},
    {"code": 24021, "name": "Châteauguay-Lacolle"},
    {"code": 24022, "name": "Chicoutimi-Le Fjord"},
    {"code": 24023, "name": "Compton-Stanstead"},
    {"code": 24024, "name": "Dorval-Lachine-LaSalle"},
    {"code": 24025, "name": "Drummond"},
    {"code": 24026, "name": "Gaspésie-Les Îles-de-la-Madeleine"},
    {"code": 24027, "name": "Gatineau"},
    {"code": 24028, "name": "Hochelaga"},
    {"code": 24029, "name": "Honoré-Mercier"},
    {"code": 24030, "name": "Hull-Aylmer"},
    {"code": 24031, "name": "Joliette"},
    {"code": 24032, "name": "Jonquière"},
    {"code": 24033, "name": "La Pointe-de-l\'Île"},
    {"code": 24034, "name": "La Prairie"},
    {"code": 24035, "name": "Lac-Saint-Jean"},
    {"code": 24036, "name": "Lac-Saint-Louis"},
    {"code": 24037, "name": "LaSalle-Émard-Verdun"},
    {"code": 24038, "name": "Laurentides-Labelle"},
    {"code": 24039, "name": "Laurier-Sainte-Marie"},
    {"code": 24040, "name": "Laval-Les Îles"},
    {"code": 24042, "name": "Lévis-Lotbinière"},
    {"code": 24041, "name": "Longueuil-Charles-LeMoyne"},
    {"code": 24043, "name": "Longueuil-Saint-Hubert"},
    {"code": 24044, "name": "Louis-Hébert"},
    {"code": 24045, "name": "Louis-Saint-Laurent"},
    {"code": 24046, "name": "Manicouagan"},
    {"code": 24065, "name": "Marc-Aurèle-Fortin"},
    {"code": 24047, "name": "Mégantic-L\'Érable"},
    {"code": 24048, "name": "Mirabel"},
    {"code": 24049, "name": "Montarville"},
    {"code": 24050, "name": "Montcalm"},
    {"code": 24051, "name": "Montmagny-L\'Islet-Kamouraska-Rivière-du-Loup"},
    {"code": 24052, "name": "Mount Royal"},
    {"code": 24053, "name": "Notre-Dame-de-Grâce-Westmount"},
    {"code": 24054, "name": "Outremont"},
    {"code": 24055, "name": "Papineau"},
    {"code": 24014, "name": "Pierre-Boucher-Les Patriotes-Verchères"},
    {"code": 24056, "name": "Pierrefonds-Dollard"},
    {"code": 24057, "name": "Pontiac"},
    {"code": 24058, "name": "Portneuf-Jacques-Cartier"},
    {"code": 24059, "name": "Québec"},
    {"code": 24060, "name": "Repentigny"},
    {"code": 24061, "name": "Richmond-Arthabaska"},
    {"code": 24018, "name": "Rimouski-Neigette-Témiscouata-Les Basques"},
    {"code": 24062, "name": "Rivière-des-Mille-Îles"},
    {"code": 24063, "name": "Rivière-du-Nord"},
    {"code": 24064, "name": "Rosemont-La Petite-Patrie"},
    {"code": 24066, "name": "Saint-Hyacinthe-Bagot"},
    {"code": 24067, "name": "Saint-Jean"},
    {"code": 24068, "name": "Saint-Laurent"},
    {"code": 24069, "name": "Saint-Léonard-Saint-Michel"},
    {"code": 24070, "name": "Saint-Maurice-Champlain"},
    {"code": 24071, "name": "Salaberry-Suroît"},
    {"code": 24072, "name": "Shefford"},
    {"code": 24073, "name": "Sherbrooke"},
    {"code": 24075, "name": "Terrebonne"},
    {"code": 24013, "name": "Thérèse-De Blainville"},
    {"code": 24076, "name": "Trois-Rivières"},
    {"code": 24074, "name": "Vaudreuil-Soulanges"},
    {"code": 24077, "name": "Ville-Marie-Le Sud-Ouest-Île-des-Sœurs"},
    {"code": 24078, "name": "Vimy"},
    {"code": 35001, "name": "Ajax"},
    {"code": 35002, "name": "Algoma-Manitoulin-Kapuskasing"},
    {"code": 35003, "name": "Aurora-Oak Ridges-Richmond Hill"},
    {"code": 35004, "name": "Barrie-Innisfil"},
    {"code": 35005, "name": "Barrie-Springwater-Oro-Medonte"},
    {"code": 35006, "name": "Bay of Quinte"},
    {"code": 35007, "name": "Beaches-East York"},
    {"code": 35008, "name": "Brampton Centre"},
    {"code": 35009, "name": "Brampton East"},
    {"code": 35010, "name": "Brampton North"},
    {"code": 35011, "name": "Brampton South"},
    {"code": 35012, "name": "Brampton West"},
    {"code": 35013, "name": "Brantford-Brant"},
    {"code": 35014, "name": "Bruce-Grey-Owen Sound"},
    {"code": 35015, "name": "Burlington"},
    {"code": 35016, "name": "Cambridge"},
    {"code": 35088, "name": "Carleton (Ontario electoral district)|Carleton"},
    {"code": 35017, "name": "Chatham-Kent-Leamington"},
    {"code": 35018, "name": "Davenport"},
    {"code": 35019, "name": "Don Valley East"},
    {"code": 35020, "name": "Don Valley North"},
    {"code": 35021, "name": "Don Valley West"},
    {"code": 35022, "name": "Dufferin-Caledon"},
    {"code": 35023, "name": "Durham"},
    {"code": 35024, "name": "Eglinton-Lawrence"},
    {"code": 35025, "name": "Elgin-Middlesex-London"},
    {"code": 35026, "name": "Essex"},
    {"code": 35027, "name": "Etobicoke Centre"},
    {"code": 35028, "name": "Etobicoke-Lakeshore"},
    {"code": 35029, "name": "Etobicoke North"},
    {"code": 35030, "name": "Flamborough-Glanbrook"},
    {"code": 35031, "name": "Glengarry-Prescott-Russell"},
    {"code": 35032, "name": "Guelph"},
    {"code": 35033, "name": "Haldimand-Norfolk"},
    {"code": 35034, "name": "Haliburton-Kawartha Lakes-Brock"},
    {"code": 35035, "name": "Hamilton Centre"},
    {"code": 35036, "name": "Hamilton East-Stoney Creek"},
    {"code": 35037, "name": "Hamilton Mountain"},
    {"code": 35038, "name": "Hamilton West-Ancaster-Dundas"},
    {"code": 35039, "name": "Hastings-Lennox and Addington"},
    {"code": 35121, "name": "Humber River-Black Creek"},
    {"code": 35040, "name": "Huron-Bruce"},
    {"code": 35041, "name": "Kanata-Carleton"},
    {"code": 35042, "name": "Kenora"},
    {"code": 35043, "name": "King-Vaughan"},
    {"code": 35044, "name": "Kingston and the Islands"},
    {"code": 35045, "name": "Kitchener Centre"},
    {"code": 35046, "name": "Kitchener-Conestoga"},
    {"code": 35047, "name": "Kitchener South-Hespeler"},
    {"code": 35048, "name": "Lambton-Kent-Middlesex"},
    {"code": 35049, "name": "Lanark-Frontenac-Kingston"},
    {"code": 35050, "name": "Leeds-Grenville-Thousand Islands and Rideau Lakes"},
    {"code": 35051, "name": "London-Fanshawe"},
    {"code": 35052, "name": "London North Centre"},
    {"code": 35053, "name": "London West"},
    {"code": 35054, "name": "Markham-Stouffville"},
    {"code": 35055, "name": "Markham-Thornhill"},
    {"code": 35056, "name": "Markham-Unionville"},
    {"code": 35057, "name": "Milton"},
    {"code": 35058, "name": "Mississauga Centre"},
    {"code": 35059, "name": "Mississauga East-Cooksville"},
    {"code": 35060, "name": "Mississauga-Erin Mills"},
    {"code": 35061, "name": "Mississauga-Lakeshore"},
    {"code": 35062, "name": "Mississauga-Malton"},
    {"code": 35063, "name": "Mississauga-Streetsville"},
    {"code": 35064, "name": "Nepean"},
    {"code": 35065, "name": "Newmarket-Aurora"},
    {"code": 35066, "name": "Niagara Centre"},
    {"code": 35067, "name": "Niagara Falls"},
    {"code": 35068, "name": "Niagara West"},
    {"code": 35069, "name": "Nickel Belt"},
    {"code": 35070, "name": "Nipissing-Timiskaming"},
    {"code": 35071, "name": "Northumberland-Peterborough South"},
    {"code": 35072, "name": "Oakville"},
    {"code": 35073, "name": "Oakville North-Burlington"},
    {"code": 35076, "name": "Orléans"},
    {"code": 35074, "name": "Oshawa"},
    {"code": 35075, "name": "Ottawa Centre"},
    {"code": 35077, "name": "Ottawa South"},
    {"code": 35078, "name": "Ottawa-Vanier"},
    {"code": 35079, "name": "Ottawa West-Nepean"},
    {"code": 35080, "name": "Oxford"},
    {"code": 35081, "name": "Parkdale-High Park"},
    {"code": 35082, "name": "Parry Sound-Muskoka"},
    {"code": 35083, "name": "Perth-Wellington"},
    {"code": 35084, "name": "Peterborough-Kawartha"},
    {"code": 35085, "name": "Pickering-Uxbridge"},
    {"code": 35086, "name": "Renfrew-Nipissing-Pembroke"},
    {"code": 35087, "name": "Richmond Hill"},
    {"code": 35089, "name": "St. Catharines"},
    {"code": 35091, "name": "Sarnia-Lambton"},
    {"code": 35092, "name": "Sault Ste. Marie"},
    {"code": 35093, "name": "Scarborough-Agincourt"},
    {"code": 35094, "name": "Scarborough Centre"},
    {"code": 35095, "name": "Scarborough-Guildwood"},
    {"code": 35096, "name": "Scarborough North"},
    {"code": 35097, "name": "Scarborough-Rouge Park"},
    {"code": 35098, "name": "Scarborough Southwest"},
    {"code": 35099, "name": "Simcoe-Grey"},
    {"code": 35100, "name": "Simcoe North"},
    {"code": 35101, "name": "Spadina-Fort York"},
    {"code": 35102, "name": "Stormont-Dundas-South Glengarry"},
    {"code": 35103, "name": "Sudbury"},
    {"code": 35104, "name": "Thornhill"},
    {"code": 35105, "name": "Thunder Bay-Rainy River"},
    {"code": 35106, "name": "Thunder Bay-Superior North"},
    {"code": 35107, "name": "Timmins-James Bay"},
    {"code": 35108, "name": "Toronto Centre"},
    {"code": 35109, "name": "Toronto-Danforth"},
    {"code": 35090, "name": "Toronto-St. Paul\'s"},
    {"code": 35110, "name": "University-Rosedale"},
    {"code": 35111, "name": "Vaughan-Woodbridge"},
    {"code": 35112, "name": "Waterloo"},
    {"code": 35113, "name": "Wellington-Halton Hills"},
    {"code": 35114, "name": "Whitby"},
    {"code": 35115, "name": "Willowdale"},
    {"code": 35116, "name": "Windsor-Tecumseh"},
    {"code": 35117, "name": "Windsor West"},
    {"code": 35118, "name": "York Centre"},
    {"code": 35119, "name": "York-Simcoe"},
    {"code": 35120, "name": "York South-Weston"},
    {"code": 46001, "name": "Brandon-Souris"},
    {"code": 46002, "name": "Charleswood-St. James-Assiniboia-Headingley"},
    {"code": 46003, "name": "Churchill-Keewatinook Aski"},
    {"code": 46004, "name": "Dauphin-Swan River-Neepawa"},
    {"code": 46005, "name": "Elmwood-Transcona"},
    {"code": 46006, "name": "Kildonan-St. Paul"},
    {"code": 46007, "name": "Portage-Lisgar"},
    {"code": 46008, "name": "Provencher"},
    {"code": 46009, "name": "Saint Boniface-Saint Vital"},
    {"code": 46010, "name": "Selkirk-Interlake-Eastman"},
    {"code": 46011, "name": "Winnipeg Centre"},
    {"code": 46012, "name": "Winnipeg North"},
    {"code": 46013, "name": "Winnipeg South"},
    {"code": 46014, "name": "Winnipeg South Centre"},
    {"code": 47001, "name": "Battlefords-Lloydminster"},
    {"code": 47004, "name": "Carlton Trail-Eagle Creek"},
    {"code": 47002, "name": "Cypress Hills-Grasslands"},
    {"code": 47003, "name": "Desnethé-Missinippi-Churchill River"},
    {"code": 47005, "name": "Moose Jaw-Lake Centre-Lanigan"},
    {"code": 47006, "name": "Prince Albert"},
    {"code": 47007, "name": "Regina-Lewvan"},
    {"code": 47008, "name": "Regina-Qu\'Appelle"},
    {"code": 47009, "name": "Regina-Wascana"},
    {"code": 47010, "name": "Saskatoon-Grasswood"},
    {"code": 47011, "name": "Saskatoon-University"},
    {"code": 47012, "name": "Saskatoon West"},
    {"code": 47013, "name": "Souris-Moose Mountain"},
    {"code": 47014, "name": "Yorkton-Melville"},
    {"code": 48001, "name": "Banff-Airdrie"},
    {"code": 48002, "name": "Battle River-Crowfoot"},
    {"code": 48003, "name": "Bow River"},
    {"code": 48004, "name": "Calgary Centre"},
    {"code": 48005, "name": "Calgary Confederation"},
    {"code": 48006, "name": "Calgary Forest Lawn"},
    {"code": 48007, "name": "Calgary Heritage"},
    {"code": 48008, "name": "Calgary Midnapore"},
    {"code": 48009, "name": "Calgary Nose Hill"},
    {"code": 48010, "name": "Calgary Rocky Ridge"},
    {"code": 48011, "name": "Calgary Shepard"},
    {"code": 48012, "name": "Calgary Signal Hill"},
    {"code": 48013, "name": "Calgary Skyview"},
    {"code": 48014, "name": "Edmonton Centre"},
    {"code": 48015, "name": "Edmonton Griesbach"},
    {"code": 48016, "name": "Edmonton Manning"},
    {"code": 48017, "name": "Edmonton Mill Woods"},
    {"code": 48018, "name": "Edmonton Riverbend"},
    {"code": 48019, "name": "Edmonton Strathcona"},
    {"code": 48020, "name": "Edmonton West"},
    {"code": 48021, "name": "Edmonton-Wetaskiwin"},
    {"code": 48022, "name": "Foothills"},
    {"code": 48023, "name": "Fort McMurray-Cold Lake"},
    {"code": 48024, "name": "Grande Prairie-Mackenzie"},
    {"code": 48025, "name": "Lakeland"},
    {"code": 48026, "name": "Lethbridge"},
    {"code": 48027, "name": "Medicine Hat-Cardston-Warner"},
    {"code": 48028, "name": "Peace River-Westlock"},
    {"code": 48030, "name": "Red Deer-Lacombe"},
    {"code": 48029, "name": "Red Deer-Mountain View"},
    {"code": 48031, "name": "St. Albert-Edmonton"},
    {"code": 48032, "name": "Sherwood Park-Fort Saskatchewan"},
    {"code": 48033, "name": "Sturgeon River-Parkland"},
    {"code": 48034, "name": "Yellowhead"},
    {"code": 59001, "name": "Abbotsford"},
    {"code": 59002, "name": "Burnaby North-Seymour"},
    {"code": 59003, "name": "Burnaby South"},
    {"code": 59004, "name": "Cariboo-Prince George"},
    {"code": 59005, "name": "Central Okanagan-Similkameen-Nicola"},
    {"code": 59006, "name": "Chilliwack-Hope"},
    {"code": 59007, "name": "Cloverdale-Langley City"},
    {"code": 59008, "name": "Coquitlam-Port Coquitlam"},
    {"code": 59009, "name": "Courtenay-Alberni"},
    {"code": 59010, "name": "Cowichan-Malahat-Langford"},
    {"code": 59011, "name": "Delta"},
    {"code": 59026, "name": "Esquimalt-Saanich-Sooke"},
    {"code": 59012, "name": "Fleetwood-Port Kells"},
    {"code": 59013, "name": "Kamloops-Thompson-Cariboo"},
    {"code": 59014, "name": "Kelowna-Lake Country"},
    {"code": 59015, "name": "Kootenay-Columbia"},
    {"code": 59016, "name": "Langley-Aldergrove"},
    {"code": 59017, "name": "Mission-Matsqui-Fraser Canyon"},
    {"code": 59018, "name": "Nanaimo-Ladysmith"},
    {"code": 59019, "name": "New Westminster-Burnaby"},
    {"code": 59037, "name": "North Island-Powell River"},
    {"code": 59020, "name": "North Okanagan-Shuswap"},
    {"code": 59021, "name": "North Vancouver"},
    {"code": 59022, "name": "Pitt Meadows-Maple Ridge"},
    {"code": 59023, "name": "Port Moody-Coquitlam"},
    {"code": 59024, "name": "Prince George-Peace River-Northern Rockies"},
    {"code": 59025, "name": "Richmond Centre"},
    {"code": 59027, "name": "Saanich-Gulf Islands"},
    {"code": 59028, "name": "Skeena-Bulkley Valley"},
    {"code": 59029, "name": "South Okanagan-West Kootenay"},
    {"code": 59030, "name": "South Surrey-White Rock"},
    {"code": 59031, "name": "Steveston-Richmond East"},
    {"code": 59032, "name": "Surrey Centre"},
    {"code": 59033, "name": "Surrey-Newton"},
    {"code": 59034, "name": "Vancouver Centre"},
    {"code": 59035, "name": "Vancouver East"},
    {"code": 59036, "name": "Vancouver Granville"},
    {"code": 59038, "name": "Vancouver Kingsway"},
    {"code": 59039, "name": "Vancouver Quadra"},
    {"code": 59040, "name": "Vancouver South"},
    {"code": 59041, "name": "Victoria"},
    {"code": 59042, "name": "West Vancouver-Sunshine Coast-Sea to Sky Country"},
    {"code": 60001, "name": "Yukon"},
    {"code": 61001, "name": "Northwest Territories"},
    {"code": 62001, "name": "Nunavut"},
];
map = document.getElementById("map")

for (var riding of data) {
    var r = document.createElement("button");
    r.className = "r" + riding.code
    r.setAttribute("style", "grid-row: 20; grid-column: 4; background-color: #FF0000");
    r.setAttribute("onHover", riding.name);
    map.appendChild(r);
};
